// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TrainersSource.InfrastructureServices.Gateways.Database;

namespace TrainersSource.WebService.Migrations
{
    [DbContext(typeof(TrainersContext))]
    [Migration("20200525191700_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.3");

            modelBuilder.Entity("TrainersSource.DomainObjects.Trainers", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Birthday")
                        .HasColumnType("TEXT");

                    b.Property<string>("Gender")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Patronymic")
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .HasColumnType("TEXT");

                    b.Property<string>("Surname")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Trainerss");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Birthday = "19.01.1973",
                            Gender = "женский",
                            Name = "Надежда",
                            Patronymic = "Викторовна",
                            Sport = "Большой спорт",
                            Surname = "Абызова"
                        },
                        new
                        {
                            Id = 2L,
                            Birthday = "01.02.1960",
                            Gender = "женский",
                            Name = "Лариса",
                            Patronymic = "Владимировна",
                            Sport = "Большой спорт",
                            Surname = "Алешина"
                        },
                        new
                        {
                            Id = 3L,
                            Birthday = "21.11.1973",
                            Gender = "мужской",
                            Name = "Алексей",
                            Patronymic = "Михайлович",
                            Sport = "Спортивный резерв",
                            Surname = "Андрюхин"
                        },
                        new
                        {
                            Id = 4L,
                            Birthday = "10.11.1957",
                            Gender = "мужской",
                            Name = "Александр",
                            Patronymic = "Львович",
                            Sport = "Большой спорт",
                            Surname = "Ануров"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
